# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guiciolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    windows_index_type = 2
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    guifont = "FuraCode Nerd Font:h11"
    filetree_direction = "left"
    enable_neomake = true
    enable_ale = true
    lint_on_the_fly = true
    error_symbol = "*"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    relativenumber = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "lang#elm"

[[layers]]
name = "colorscheme"
enable = true

[[layers]]
name = "ale"
enable = true

[[layers]]
name = "checkers"
enable = true

[[layers]]
name = 'denite.vim'
enable = true

[[custom_plugins]]
name = "Shougo/vimproc.vim"
merged = false

[[custom_plugins]]
name = "lilydjwg/colorizer"
on_cmd = ["ColorHighlight", "ColorToggle"]
merged = false
